name: Build Test

on:
  push:
    branches:
      - convert-frontend-to-angular
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: npm install, build, and test - ANGULAR
        run: |
          npm install @angular/cli
          npm install
          npm run build
        working-directory: ./IncidentManagerClient

      - name: npm install, build, and test - SERVER
        run: |
          npm install
      - name: Upload server artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: |
            *
            !IncidentManagerClient
            
      - name: Upload front artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: IncidentManagerClient/dist

  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v2
          with:
            name: node-app

        - name: 'Deploy to Azure Web App'
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'comp229-group3'
            slot-name: 'Production'
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2600471B2CAA4B5DBBA4A2E06ED64714 }}
            package: .
